### ISSUE TITLE
incorrection and missing information of Japan's Type 87 

### ISSUE THREAD

**Issue by Rikkalxn** [ImVexed/ThunderView#27]
The vehicle icon of Japan's Type 87 in Ground Thermals is incorrect, it should be a SPAA icon instead of a MBT icon. And in the category of ground radar, Type 87 is not in the list.

If you see this issue, I hope you can add and modify the relevant data as soon as possible.

here is the image
![image](https://github.com/ImVexed/ThunderView/assets/84234793/5c108e30-4cb0-4f75-ad70-9347b6bee907)
![image](https://github.com/ImVexed/ThunderView/assets/84234793/5c8a74b8-6868-492b-9d85-15496ca76dc7)

**Comment by ImVexed** [comment]
I have no idea why the Type 87 is coded as a heavy in the data files `"subclass": "heavyVehicle",` for some reason. 
I probably won't fix this, as it's technically correct according to the game files. Though I agree it doesn't make much sense. I'd have to start putting caveats any place we check vehicle type just in case it's the Type 87, which seems quite annoying. 

The radar, however, has been fixed in a recent commit.
